// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pipeline-motion/AmbientGlow.tsx": () => import("../components/mockups/pipeline-motion/AmbientGlow.tsx"),
  "./components/mockups/pipeline-motion/DataFlow.tsx": () => import("../components/mockups/pipeline-motion/DataFlow.tsx"),
  "./components/mockups/pipeline-motion/ScrollReveal.tsx": () => import("../components/mockups/pipeline-motion/ScrollReveal.tsx")
};
